export enum IndicatorFieldType {
  Interval = "Interval",
  Crossing = "Crossing",
  IncludeCurrentPrice = "IncludeCurrentPrice",
  Period = "Period",
  Period1 = "Period1",
  Period2 = "Period2",
  HasJustCrossed = "HasJustCrossed",
  IsHolding = "IsHolding",
  Length = "Length",
  Multiplier = "Multiplier",
  CrossingBand = "CrossingBand",
  IsBuy = "IsBuy",
  PercentageChange = "PercentageChange",
  AmountChange = "AmountChange",
  PriceTarget = "PriceTarget",
  TrailingStopPercentage = "TrailingStopPercentage",
  RSIThreshold = "RSIThreshold",
}
