trigger:
  - master

variables:
  webAppName: 'crypto-manager-server'

stages:
  - stage: Build
    displayName: Build stage

    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: windows-latest

        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: '**/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: '**/*Test/*.csproj'
              arguments: '--collect "Code coverage"'

          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'

  - stage: Test_deployment
    displayName: Test deployment
    variables:
      - template: azure-variables.yml
        parameters:
          environment: 'test'
    jobs:
      - template: azure-deploy.yml
        parameters:
          environment: 'test'
          azureSubscription: 'sentinel-trader-sc-test'
          webAppName: $(webAppName)

  - stage: Prod_deployment
    displayName: Prod deployment
    variables:
      - template: azure-variables.yml
        parameters:
          environment: 'prod'
    jobs:
      - template: azure-deploy.yml
        parameters:
          environment: 'prod'
          azureSubscription: 'sentinel-trader-sc-prod'
          webAppName: $(webAppName)
